name: ubuntu-desktop-session
adopt-info: ubuntu-desktop-session
summary: Ubuntu Desktop Session for the Ubuntu Core Desktop
description: |
  A strictly confined Ubuntu Desktop session for Ubuntu Core Desktop.

grade: stable
confinement: strict
base: core24
platforms:
  all:
    build-on: amd64
    build-for: all

package-repositories:
 - type: apt
   ppa: desktop-snappers/core-desktop

environment:
  HOME: $SNAP_REAL_HOME
  XDG_CACHE_HOME: $SNAP_USER_COMMON/.cache
  XDG_CONFIG_HOME: $SNAP_USER_COMMON/.config
  XDG_DATA_HOME: $SNAP_USER_COMMON/.local/share
  XDG_STATE_HOME: $SNAP_USER_COMMON/.local/state
  LD_LIBRARY_PATH: ${LD_LIBRARY_PATH:+$LD_LIBRARY_PATH:}$SNAP/usr/lib:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/gnome-shell:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/mutter-14:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pulseaudio:$SNAP/usr/lib/gnome-settings-daemon-46:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libunity
  GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas${GSETTINGS_SCHEMA_DIR:+:$GSETTINGS_SCHEMA_DIR}
  GI_TYPELIB_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gjs/girepository-1.0:$SNAP/usr/lib/gnome-shell:$SNAP/usr/lib/gnome-shell/girepository-1.0:$SNAP/usr/lib/girepository-1.0:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/mutter-14${GI_TYPELIB_PATH:+:$GI_TYPELIB_PATH}

layout:
  /usr/share/libinput:
    symlink: $SNAP/usr/share/libinput
  /usr/share/gnome-shell:
    bind: $SNAP/usr/share/gnome-shell
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0/2.10.0:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0/2.10.0
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/dri
  /usr/share/glvnd:
    bind: $SNAP/usr/share/glvnd
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/share/xml/iso-codes:
    bind: $SNAP/usr/share/xml/iso-codes
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgweather-4:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgweather-4
  /etc/fonts:
    bind: $SNAP/etc/fonts
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /usr/share/fontconfig:
    bind: $SNAP/usr/share/fontconfig
  /usr/share/themes:
    bind: $SNAP/usr/share/themes
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /etc/mime.types:
    bind-file: $SNAP/etc/mime.types
  /usr/share/mime:
    bind: $SNAP/usr/share/mime
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/glib-2.0:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/glib-2.0

apps:
  ubuntu-desktop-session:
    command: run-session.sh
    slots:
      - wayland
      - x11
      - desktop
#      - dbus-gnome-mutter-service-channel
    plugs: &pluglist
      - account-control
      - audio-playback
      - audio-record
      - avahi-control
      - bluetooth-control
      - bluez
      - cups-control
      - desktop-launch
      - hardware-observe
      - hostname-control
      - home
      - locale-control
      - login-session-observe
      - login-session-control
      - mount-observe
      - network-bind
      - network-control
      - network-observe
      - network-manager
      - opengl
      - polkit-agent
      - process-control
      - shell-session-locale-files
      - shutdown
      - ssh-keys
      - system-observe
      - time-control
      - timeserver-control
      - timezone-control
      - upower-observe

  screencast-service:
    command: run.sh $SNAP/usr/bin/gjs -m /usr/share/gnome-shell/org.gnome.Shell.Screencast
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gnome-shell-screencast
    restart-delay: 1s
    plugs: *pluglist

  nautilus-service:
    command: run.sh $SNAP/usr/bin/nautilus --gapplication-service
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gnome-nautilus
    restart-delay: 1s
    plugs: *pluglist

  xdg-desktop-portal-gnome:
    command: run.sh $SNAP/usr/libexec/xdg-desktop-portal-gnome
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-freedesktop-impl-portal-gnome
    restart-delay: 1s
    plugs: *pluglist

  #xdg-desktop-portal-gtk:
  #  command: run.sh /usr/libexec/xdg-desktop-portal-gtk
  #  daemon: dbus
  #  daemon-scope: user
  #  activates-on:
  #    - dbus-freedesktop-impl-portal-gtk
  #  restart-delay: 1s

  ibus-service:
    command: run.sh $SNAP/usr/bin/ibus-daemon --panel disable
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-ibus
    restart-delay: 1s
    plugs: *pluglist

  ibus-gtk3-service:
    command: run.sh $SNAP/usr/libexec/ibus-extension-gtk3
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-ibus-gtk3
    restart-delay: 1s
    plugs: *pluglist

  ibus-portal-service:
    command: run.sh $SNAP/usr/libexec/ibus-portal
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-ibus-portal
    restart-delay: 1s
    plugs: *pluglist

  colord:
    command: run.sh $SNAP/usr/libexec/colord-session
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-colord
    restart-delay: 1s
    plugs: *pluglist

  calendar-server:
    command: run.sh $SNAP/usr/libexec/gnome-shell-calendar-server
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gnome-shell-calendar-server
    restart-delay: 1s
    plugs: *pluglist

  gtk-settings:
    command: run.sh $SNAP/usr/libexec/gsd-xsettings
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gtk-settings
    restart-delay: 1s
    plugs: *pluglist

  gnome-settings:
    command: run.sh $SNAP/usr/bin/gnome-control-center
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gnome-settings
    restart-delay: 1s
    plugs: *pluglist

  gnome-settings-a11y:
    command: run.sh $SNAP/usr/libexec/gsd-a11y-settings
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gsd-a11ysettings
    restart-delay: 1s
    plugs: *pluglist

  gnome-settings-color:
    command: run.sh $SNAP/usr/libexec/gsd-color
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gsd-color
    restart-delay: 1s
    plugs: *pluglist

  gnome-settings-datetime:
    command: run.sh $SNAP/usr/libexec/gsd-datetime
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gsd-datetime
    restart-delay: 1s
    plugs: *pluglist

  gnome-settings-housekeeping:
    command: run.sh $SNAP/usr/libexec/gsd-housekeeping
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gsd-housekeeping
    restart-delay: 1s
    plugs: *pluglist

  gnome-settings-keyboard:
    command: run.sh $SNAP/usr/libexec/gsd-keyboard
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gsd-keyboard
    restart-delay: 1s
    plugs: *pluglist

  gnome-settings-media-keys:
    command: run.sh $SNAP/usr/libexec/gsd-media-keys
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gsd-mediakeys
    restart-delay: 1s
    plugs: *pluglist

  gnome-settings-power:
    command: run.sh $SNAP/usr/libexec/gsd-power
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gsd-power
    restart-delay: 1s
    plugs: *pluglist

  gnome-settings-print-notifications:
    command: run.sh $SNAP/usr/libexec/gsd-print-notifications
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gsd-printnotifications
    restart-delay: 1s
    plugs: *pluglist

  gnome-settings-rfkill:
    command: run.sh $SNAP/usr/libexec/gsd-rfkill
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gsd-rfkill
    restart-delay: 1s
    plugs: *pluglist

  gnome-settings-screensaver-proxy:
    command: run.sh $SNAP/usr/libexec/gsd-screensaver-proxy
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gsd-screensaverproxy
    restart-delay: 1s
    plugs: *pluglist

  gnome-settings-sharing:
    command: run.sh $SNAP/usr/libexec/gsd-sharing
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gsd-sharing
    restart-delay: 1s
    plugs: *pluglist

  gnome-settings-smartcard:
    command: run.sh $SNAP/usr/libexec/gsd-smartcard
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gsd-smartcard
    restart-delay: 1s
    plugs: *pluglist

  gnome-settings-sound:
    command: run.sh $SNAP/usr/libexec/gsd-sound
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gsd-sound
    restart-delay: 1s
    plugs: *pluglist

  gnome-settings-usb-protection:
    command: run.sh $SNAP/usr/libexec/gsd-usd-protection
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gsd-usbprotection
    restart-delay: 1s
    plugs: *pluglist

  gnome-settings-wacom:
    command: run.sh $SNAP/usr/libexec/gsd-wacom
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gsd-wacom
    restart-delay: 1s
    plugs: *pluglist

  gnome-settings-xsettings:
    command: run.sh $SNAP/usr/libexec/gsd-xsettings
    daemon: dbus
    passthrough:
      daemon-scope: user
    activates-on:
      - dbus-gsd-xsettings
    restart-delay: 1s
    plugs: *pluglist

plugs:
  dot-local-share-nautilus:
    interface: personal-files
    write:
      - $HOME/.local/share/nautilus
  dot-hidden:
    interface: personal-files
    write:
      - $HOME/.hidden
  shell-session-locale-files:
    interface: personal-files
    write:
      - $HOME/.pam_environment
      - $HOME/.xinputrc
  shell-config-files:
    interface: system-files
    read:
      - /etc/fonts
      - /etc/glvnd
      - /etc/gnome/defaults.list
      - /etc/gtk-3.0
      - /etc/pulse
      - /etc/shells
      - /etc/xdg/autostart
      - /run/udev/tags/seat
      - /etc/default/im-config
      - /etc/X11/xinit/xinputrc
      - /etc/default/locale

slots:
  dbus-canonical-unity:
    interface: dbus
    bus: session
    name: com.canonical.Unity
  dbus-freedesktop-impl-portal-gnome:
    interface: dbus
    bus: session
    name: org.freedesktop.impl.portal.desktop.gnome
  dbus-freedesktop-impl-portal-gtk:
    interface: dbus
    bus: session
    name: org.freedesktop.impl.portal.desktop.gtk
  dbus-freedesktop-screensaver:
    interface: dbus
    bus: session
    name: org.freedesktop.ScreenSaver
  dbus-freedesktop-secrets:
    interface: dbus
    bus: session
    name: org.freedesktop.secrets
  dbus-gnome-cc:
    interface: dbus
    bus: session
    name: org.gnome.ControlCenter
  dbus-gnome-cc-search:
    interface: dbus
    bus: session
    name: org.gnome.ControlCenter.SearchProvider
  dbus-gnome-keyring:
    interface: dbus
    bus: session
    name: org.gnome.keyring
  dbus-gnome-keyring-sysprompter:
    interface: dbus
    bus: session
    name: org.gnome.keyring.SystemPrompter
  dbus-gnome-magnifier:
    interface: dbus
    bus: session
    name: org.gnome.Magnifier
  dbus-gnome-mutter-displayconfig:
    interface: dbus
    bus: session
    name: org.gnome.Mutter.DisplayConfig
  dbus-gnome-mutter-idlemonitor:
    interface: dbus
    bus: session
    name: org.gnome.Mutter.IdleMonitor
  dbus-gnome-mutter-remotedesktop:
    interface: dbus
    bus: session
    name: org.gnome.Mutter.RemoteDesktop
  dbus-gnome-mutter-screencast:
    interface: dbus
    bus: session
    name: org.gnome.Mutter.ScreenCast
  #dbus-gnome-mutter-service-channel:
  #  interface: dbus
  #  bus: session
  #  name: org.gnome.Mutter.ServiceChannel
  dbus-gnome-panel:
    interface: dbus
    bus: session
    name: org.gnome.Panel
  dbus-gnome-screensaver:
    interface: dbus
    bus: session
    name: org.gnome.ScreenSaver
  dbus-gnome-sessionmanager:
    interface: dbus
    bus: session
    name: org.gnome.SessionManager
  dbus-gnome-shell-calendar-server:
    interface: dbus
    bus: session
    name: org.gnome.Shell.CalendarServer
  dbus-gsd:
    interface: dbus
    bus: session
    name: org.gnome.Settings
  dbus-gsd-a11ysettings:
    interface: dbus
    bus: session
    name: org.gnome.SettingsDaemon.A11ySettings
  dbus-gsd-color:
    interface: dbus
    bus: session
    name: org.gnome.SettingsDaemon.Color
  dbus-gsd-datetime:
    interface: dbus
    bus: session
    name: org.gnome.SettingsDaemon.Datetime
  dbus-gsd-housekeeping:
    interface: dbus
    bus: session
    name: org.gnome.SettingsDaemon.Housekeeping
  dbus-gsd-keyboard:
    interface: dbus
    bus: session
    name: org.gnome.SettingsDaemon.Keyboard
  dbus-gsd-mediakeys:
    interface: dbus
    bus: session
    name: org.gnome.SettingsDaemon.MediaKeys
  dbus-gsd-power:
    interface: dbus
    bus: session
    name: org.gnome.SettingsDaemon.Power
  dbus-gsd-printnotifications:
    interface: dbus
    bus: session
    name: org.gnome.SettingsDaemon.PrintNotifications
  dbus-gsd-rfkill:
    interface: dbus
    bus: session
    name: org.gnome.SettingsDaemon.Rfkill
  dbus-gsd-screensaverproxy:
    interface: dbus
    bus: session
    name: org.gnome.SettingsDaemon.ScreensaverProxy
  dbus-gsd-sharing:
    interface: dbus
    bus: session
    name: org.gnome.SettingsDaemon.Sharing
  dbus-gsd-smartcard:
    interface: dbus
    bus: session
    name: org.gnome.SettingsDaemon.Smartcard
  dbus-gsd-sound:
    interface: dbus
    bus: session
    name: org.gnome.SettingsDaemon.Sound
  dbus-gsd-usbprotection:
    interface: dbus
    bus: session
    name: org.gnome.SettingsDaemon.UsbProtection
  dbus-gsd-wacom:
    interface: dbus
    bus: session
    name: org.gnome.SettingsDaemon.Wacom
  dbus-gsd-wwan:
    interface: dbus
    bus: session
    name: org.gnome.SettingsDaemon.Wwan
  dbus-gsd-xsettings:
    interface: dbus
    bus: session
    name: org.gnome.SettingsDaemon.XSettings
  dbus-gnome-nautilus:
    interface: dbus
    bus: session
    name: org.gnome.Nautilus
  dbus-gnome-shell:
    interface: dbus
    bus: session
    name: org.gnome.Shell
  dbus-gnome-shell-audio:
    interface: dbus
    bus: session
    name: org.gnome.Shell.AudioDeviceSelection
  dbus-gnome-shell-introspect:
    interface: dbus
    bus: session
    name: org.gnome.Shell.Introspect
  dbus-gnome-shell-portal:
    interface: dbus
    bus: session
    name: org.gnome.Shell.Portal
  dbus-gnome-shell-screencast:
    interface: dbus
    bus: session
    name: org.gnome.Shell.Screencast
  dbus-gnome-shell-screenshot:
    interface: dbus
    bus: session
    name: org.gnome.Shell.Screenshot
  dbus-gnome-shell-wacom:
    interface: dbus
    bus: session
    name: org.gnome.Shell.Wacom.PadOsd
  dbus-gnome-settings:
    interface: dbus
    bus: session
    name: org.gnome.Settings
  dbus-gnome-terminal:
    interface: dbus
    bus: session
    name: org.gnome.Terminal
  dbus-gtk-mountoperationhandler:
    interface: dbus
    bus: session
    name: org.gtk.MountOperationHandler
  dbus-gtk-notifications:
    interface: dbus
    bus: session
    name: org.gtk.Notifications
  dbus-gtk-settings:
    interface: dbus
    bus: session
    name: org.gtk.Settings
  dbus-kde-statusnotifier:
    interface: dbus
    bus: session
    name: org.kde.StatusNotifierWatcher
  dbus-desktop-icons:
    interface: dbus
    bus: session
    name: com.rastersoft.ding
  dbus-desktop-icons-extension:
    interface: dbus
    bus: session
    name: com.rastersoft.dingextension
  dbus-portal:
    interface: dbus
    name: org.freedesktop.impl.portal.PermissionStore
    bus: session
  dbus-ibus:
    interface: dbus
    name: org.freedesktop.IBus
    bus: session
  dbus-ibus-gtk3:
    interface: dbus
    name: org.freedesktop.IBus.Panel.Extension.Gtk3
    bus: session
  dbus-ibus-portal:
    interface: dbus
    name: org.freedesktop.portal.IBus
    bus: session
  dbus-colord:
    interface: dbus
    name: org.freedesktop.ColorHelper
    bus: session

lint:
  ignore:
    - classic

parts:
  scripts:
    plugin: dump
    source: ./scripts

  ubuntu-desktop-session:
    plugin: nil
    build-packages:
      - git
    override-build: |
      cd $CRAFT_PROJECT_DIR
      craftctl set version=$(date +%Y%m%d)+git$(git rev-parse --short HEAD)

  packages:
    plugin: nil
    build-packages:
      - libglib2.0-bin
    stage-packages:
      - alsa-ucm-conf
      - fonts-ubuntu
      - gir1.2-clutter-1.0
      - gir1.2-dbusmenu-glib-0.4
      - gir1.2-gsound-1.0
      - gir1.2-glib-2.0-dev
      - gkbd-capplet
      - gnome-control-center
      - gnome-keyring
      - gnome-menus
      - gnome-settings-daemon
      - gnome-shell
      - gnome-shell-common
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-desktop-icons-ng
      - gnome-shell-extension-ubuntu-dock
      - gnome-shell-extension-ubuntu-tiling-assistant
      - gsound-tools
      - ibus
      - inotify-tools
      - iso-codes
      - libcanberra-pulse
      - libfreetype6
      - libgdk-pixbuf-2.0-0
      - libgjs0g
      - libgl1-mesa-dri
      - libgsound0
      - libpam-gnome-keyring
      - libsnapd-glib-2-1
      - libsysmetrics1
      - locales-all
      - locales
      - media-types
      - polkitd
      - pulseaudio-utils
      - ubuntu-session
      - ubuntu-settings
      - xdg-desktop-portal
      - xdg-desktop-portal-gnome
      - xdg-desktop-portal-gtk
      - xdg-user-dirs-gtk
      - xdg-user-dirs
      - xkb-data
      - xwayland
      - yaru-theme-gtk
      - yaru-theme-gnome-shell
      - yaru-theme-icon
    build-environment:
      - LD_LIBRARY_PATH: $CRAFT_PART_INSTALL/usr/lib:$CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
    override-build: |
      # compile schemas
      glib-compile-schemas $CRAFT_PART_INSTALL/usr/share/glib-2.0/schemas
      # update pixbuf-loaders cache
      export CACHE=$CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0/2.10.0/loaders.cache
      $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0/2.10.0/loaders/* > $CACHE
      sed -i "s@$CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0/2.10.0@/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gdk-pixbuf-2.0/2.10.0@g" $CACHE
      # update MIME types
      $CRAFT_PART_INSTALL/usr/bin/update-mime-database $CRAFT_PART_INSTALL/usr/share/mime
      craftctl default

